### ISSUE TITLE
$inview is always true

### ISSUE THREAD

**Issue by Script-Shiva** [thenikso/angular-inview#104]
How to know when an element goes out of view. In the in-view directive I am doing a check if the element is in view or not. But every time the $inview is returning true. I am implementing an infinite scroll and i need the binded the elements with certain properties when they are in view and remove them when they are out of view.

**Comment by bgadiel** [comment]
Have you find a solution for your problem?
Having the same issue here.

**Comment by thenikso** [comment]
could you give us some example/code? the examples provided in the repo should cover the infinite scroll scenario

**Comment by thenikso** [comment]
Please try v2 #107 and let me know if it happens again. Closing this for now. Feel free to reopen if it this issue still comes up.
