### ISSUE TITLE
angular-inview.spec.js in v2.0.0-beta.1

### ISSUE THREAD

**Issue by pvnr0082t** [thenikso/angular-inview#108]
Hi @thenikso ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team. I found that there is a new file called: `angular-inview.spec.js` in v2.0.0-beta.1. Could you please tell me if it need to be added in `cdnjs`?
Thank you.

https://github.com/cdnjs/cdnjs/issues/8777

**Comment by thenikso** [comment]
hi there. that is a file with tests so no, it doesn't need to be added to CDN for consumption purposes. same goes for beta.2 and v2.0 just released. I'll make sure to add an `.npmignore` for the next releases
