### ISSUE TITLE
Negative offset

### ISSUE THREAD

**Issue by DeadcatDev** [thenikso/angular-inview#117]
Hi,

is it possible to give it a nagative offset? Like:

 <span
        in-view="controler.someFunc($inviewInfo)"
        in-view-options="{offset: -100}"
    ></span>

It's very usable when we have fixed menu or that kind of stuff, so inView will trigger "amount of space" before it will get out from screen.

**Comment by thenikso** [comment]
yes, negative offsets are supported. you should just try it out!
