### ISSUE TITLE
does this actually require 1.5.8

### ISSUE THREAD

**Issue by richsoni** [thenikso/angular-inview#125]
I have a project running 1.5.3 and it seems to work fine.  What functionality from 1.5.8 is actually required?

**Comment by isherwood** [comment]
Usually when you see a package.json Angular version in a project like this it's for the demos and unit tests and not a direct indication of the requirement of the directive.

**Comment by thenikso** [comment]
I've updated it to be `>=1.0.0 < 2.0.0`. This might eventually be released
