### ISSUE TITLE
How to manually trigger the inview check?

### ISSUE THREAD

**Issue by polyclick** [thenikso/angular-inview#13]
Reading through the code I noticed that the inview check gets triggered at link time & when scrolling the page. But I'm wondering how I should trigger the check manually.

**Comment by marcelinhov2** [comment]
Is there a way to simple trigger all the in-view methods again? Like a reboot...

**Comment by thenikso** [comment]
You could try `angular.element(window).triggerHandler('checkInView')`

**Comment by gdpelican** [comment]
I'm trying to make this happen in conjunction with https://github.com/oblador/angular-scroll, which doesn't appear to be working. The above suggestion is not working for me.

```
let e = document.querySelector('.scroll-container')
angular.element(e).scrollToElement(e)
```

Internally, that package seems to do a manual animation thing, where it manually sets the `scrollTop` and `scrollLeft` properties of the container element (which doesn't seem to trigger the appropriate scroll event)

So having a way to manually trigger the inView after I know the scroll is complete would be ideal.

**Comment by thenikso** [comment]
I can't seam to reproduce a case where the `triggerHandler` example above isn't working. Could you try to reproduce the problem in a JSBin like https://jsbin.com/sinoba/edit?html,js,output ?

**Comment by gdpelican** [comment]
Hm.. not sure what was up with my previous workflow, but I was able to get that command to go this afternoon. Sorry for the hassle!

**Comment by thenikso** [comment]
no problem, great to know! I think this issue will help others when facing the same problem.
