### ISSUE TITLE
2.2.0 is not published to npm

### ISSUE THREAD

**Issue by szimek** [thenikso/angular-inview#130]
The latest version is still 2.1.0 there.

**Comment by thenikso** [comment]
hmm, according to npm 2.2 is there but not as the latest. This hints that at some point it was the latest but some regression made me revert to 2.1. I can't tell xD

what do you need 2.2 for? would you be able to try it out and see if it works properly?

**Comment by jjabba** [comment]
Running `npm outdated`yeilds:
```
Package                                Current  Wanted  Latest
angular-inview                           2.1.0   2.3.0   2.1.0
```
Is there any reason why 2.3.0 is not marked as the latest yet?

**Comment by thenikso** [comment]
it was badly broken I believe. `3.1.0` is the latest release
