### ISSUE TITLE
no longer finds zero height divs visible

### ISSUE THREAD

**Issue by graingert** [thenikso/angular-inview#135]

**Comment by thenikso** [comment]
I have reverted back the latest version on npm to 2.1.0 as there has been some problems with merged PRs.

Unfortunately I do not have much time to support this package

**Comment by graingert** [comment]
Can you re-release 2.1.0 as 2.3.1 and deprecate 2.3.0?

On 27 Sep 2017 10:01, "Nicola Peduzzi" <notifications@github.com> wrote:

Closed #135 <https://github.com/thenikso/angular-inview/issues/135>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/thenikso/angular-inview/issues/135#event-1267337289>,
or mute the thread
