### ISSUE TITLE
Not working for me on window scrolling

### ISSUE THREAD

**Issue by exetera** [thenikso/angular-inview#138]
Hi,
the directive is not working for me, as well as examples "basic" and "throttle".

As far as I understood, the angular expression in the "in-view" parameter should be evaluated every time the window scrolls.  In my case the expression is evaluated just when the page is loaded.

This is my html
```
<div in-view="start($inview)" class="row">
            <div class="col-lg-4">
                <center >
                    <div easypiechart options="options1" percent="percent1">
                        <span class="percent" id="percent1">{{currentpercent1}}</span>
                    </div>
                    <p class="sottotorta">vendite al mese</p> 
                    <p class="psottotorta">Il numero degli acquisti effettuati dai gruppi di acquisto presenti su Grouply</p>  
                </center>
            </div>
</div>
```
and this is a portion of my js:

```
$scope.start = function($inview){
			console.log("inview" + $inview);	  		
  }
```

The log apperas in the js console just when I reload the page and the div is already in the view.

Am I forgetting something?

Thanks

**Comment by assafganor** [comment]
It doesn't work for me too.
It works only when I use 'in-view-container'.
I think it is related to function signalFromEvent and [Fix#102](https://github.com/thenikso/angular-inview/commit/2f8628346cbc9c9b08367163043be5e531a8cc1b#diff-9c7dcc4da84fcc64a02e7e362a6209c8).
addEventListener cannot get multiple events.
Replacing line 362:
el[0].addEventListener(event, handler, true);
with:
event.split(' ').map(e => el[0].addEventListener(e, handler, true));
solved the problem for me.

**Comment by apoplexe** [comment]
it's a general question : is this directive gonna be maintain ?

**Comment by jacksonrdlc** [comment]
@assafganor This should be included. When using Chrome on a PC, the inView component would work once and then never again which made my use of the component for infinite scrolling not quite _infinite_. Thank you very much.

**Comment by thenikso** [comment]
thank you guys! this is now in v3!
