### ISSUE TITLE
[3.0.0] Syntax Error

### ISSUE THREAD

**Issue by regnete** [thenikso/angular-inview#139]
Great module!

I tried to upgrade my application from version 2.3.0 to 3.0.0.

Loading angular-inview in a cordova app on windows 10 triggers a javascript syntax error.
I tracked it down to be caused by the following to lines:

https://github.com/thenikso/angular-inview/blob/master/angular-inview.js#L363
https://github.com/thenikso/angular-inview/blob/master/angular-inview.js#L365

The issue disapears when I go back to version 2.3.0 of angular-inview.

**Comment by lbthomsen** [comment]
I think it's this one https://github.com/thenikso/angular-inview/commit/389aa6490a9b0824994286855ed22f27274939c2 and it also screws up grunt-contrib-uglify

**Comment by ViieeS** [comment]
Same thing for me.

**Comment by ViieeS** [comment]
Same thing for me.

@regnete I suggest you to rename the issue to `[3.0.0] Syntax Error`

**Comment by osro** [comment]
Yep, same issue here. Uglify fails on this.

> GulpUglifyError: unable to minify JavaScript

**Comment by mathiasmoeller** [comment]
@thenikso any chance this will be fixed?

**Comment by pire** [comment]
@mathiasmoeller there are currently 2 PRs which fix this issue.

https://github.com/thenikso/angular-inview/pull/146
https://github.com/thenikso/angular-inview/pull/145

They both have the same changes, so if you need a quick fix you could use the code in them for the time being?

I can confirm they work!

**Comment by mathiasmoeller** [comment]
@pire thanks. I already forked the repo and fixed it for myself ;)

**Comment by WebTechnolog** [comment]
@pire any chance this fixes get to the master branch?

**Comment by pire** [comment]
> @pire any chance this fixes get to the master branch?

Oh dear I missed this! Happy new year!

 I am but a humble user... I think we better ask @thenikso to accept one of the PRs I listed?
