### ISSUE TITLE
arrow functions not supported

### ISSUE THREAD

**Issue by bezzad** [thenikso/angular-inview#148]
I have an angularjs project which created by Typescript 3 with target `es5`.
In this version of javascript the arrow functions => has not been supported.
like below codes:

```
map(e => el[0].addEventListener(e, handler, true));
```

**Comment by MrXploder** [comment]
I can make a pull-request changing the es6 arrow function for regular functions

**Comment by thenikso** [comment]
#142 has been merged and released to npm as version `3.1.0`!
