### ISSUE TITLE
inViewOffset relative to scroll height?

### ISSUE THREAD

**Issue by fidoboy** [thenikso/angular-inview#26]
Would be a very useful feature to specify the offset relative to the scrollable area height, so, if for example, the scroll area height is 300px then indicating in-view-offset-rel="[-1,1]" the offset should be -300px and 300px.  And if i use  in-view-offset-rel="[-0.5,0.5]" then the offset should be -150px and 150px. This way, if the scrollable area changes it's size the offset keeps working anyway… What do you think? do you think that something like this could be added to angular-inview?

thanks,

**Comment by thenikso** [comment]
close for inactivity
