### ISSUE TITLE
allow for in-view-offset as a percentage of viewport

### ISSUE THREAD

**Issue by stephengardner** [thenikso/angular-inview#34]
instead of just a numerical value, allow a user to trigger the inview callback after the item in question has reached, for example, the top 50% of the viewport.

In this case, in-view-offset could be a percentage based on the bottom or top offset of the screen.

**Comment by ahmehri** [comment]
As @stephengardner mentioned, the scroll direction parameter feature is very important, when will be implemented?

**Comment by thenikso** [comment]
this will finally be a thing in v2
