### ISSUE TITLE
in-view event triggered at page load for out-of-view elements with no debounce

### ISSUE THREAD

**Issue by thenikso** [thenikso/angular-inview#37]
As noted by @urecio in #36, if some elements have a debounce set via `in-view-options`, those element without options, trigger the in-view event at page load even if they are out of the viewport.

TODO:

- [ ] Make a unit test to verify the bug
- [ ] Fix the bug

**Comment by mauricio-gamboa** [comment]
Hi! Will you have a fix for this bug soon? Thanks! Great plugin :+1:

**Comment by thenikso** [comment]
should be fixed in v2
