### ISSUE TITLE
in-view directive not triggering unless click event follows for absolutely-positioned container scrolling

### ISSUE THREAD

**Issue by thynctank** [thenikso/angular-inview#39]
The name says most all of what's happening.

I discovered this directive and used it to solve an issue where I needed lots of instances of Angular Bootstrap's popup-datepicker, which has VERY terrible init time, so this avoided instantiating dozens of times and locking up the browser.

At some point after getting around to styling the page, (I just noticed this so I can't pinpoint a cause) in-view stopped triggering for overflow scrolling of the container.

When this did work, I never even thought to add an `in-view-container` attribute on the overflowed element, but now I have. No change.

Even stranger, I have been able to trigger in-view expressions by clicking on the page after scrolling. I can wait arbitrary periods of time and it will not fire until I've clicked.

Any idea what might be going on? I haven't looked into alternatives and admit I haven't dug into the internals yet.

Thanks!

**Comment by thenikso** [comment]
the click works because it's an event watched on the window to refresh the inview status of all inview elements.

`in-view-container` should do the trick but there are issues with the way it calculates the boundaries of elements when absolutely positioned.

Could you find out a workaround for your issue in the mean time?

I'm working on a v2 of the directive but I don't have much time to finish it up at the moment. that version should have containers working properly. keep an eye on the [develop branch](https://github.com/thenikso/angular-inview/tree/develop) for updates

**Comment by b0jan** [comment]
Any updates on this issue?

**Comment by cheahkhing** [comment]
Hi, i am still having the same issue here. Is this being fixed?

**Comment by 0101adm** [comment]
same issue.  

scrolling does not fire.  only clicking.

**Comment by carabloomfield** [comment]
I'm also having the same issue.  Has anyone found a work around?

**Comment by mkoczorowski** [comment]
I haven't found neither  a workaround of a different module which would actually work on scroll work :/ Help please

**Comment by manoj529** [comment]
I have the same issue, I used it in ionic framework ion item it only triggers when i click on some element which has click function. Did anyone else found any other plugin which is working. Thanq for any update on this.

**Comment by smaier** [comment]
same here - no solution found

**Comment by manoj529** [comment]
@smaier try in-view-container on ion-content... That solved for me initially I kept it on ion scroll and it didn't worked for me when. I defined it on ion content it worke

**Comment by shprink** [comment]
in-view-container on ion-content worked for me too

**Comment by vinaynb** [comment]
Same behaviour for me too. Not working for me when under in-view-container.

**Comment by manoj529** [comment]
Just put the container-in-view class to ion-content

**Comment by vinaynb** [comment]
@manoj529 i am not using ionic

**Comment by svitzer** [comment]
On line 189 in angular-inview.js change to this:

return angular.element(window).bind('checkInView click ready wheel mousewheel DomMouseScroll MozMousePixelScroll resize', windowEventsHandler);

**Comment by vinaynb** [comment]
it works ! Thanks :+1:

**Comment by vinaynb** [comment]
@svitzer Can u check if it works for you in Chrome Version 48.0.2564.82 (64-bit) ? Doesn't work for me.

**Comment by alejandroiglesias** [comment]
I'm having the same issue even with version `3.0.0`. @thenikso did you made any updates related to this issue?
