### ISSUE TITLE
consider publishing to npm as well

### ISSUE THREAD

**Issue by nmccready** [thenikso/angular-inview#43]
Hope all is well :) 

I currently manage https://github.com/angular-ui/angular-google-maps and I have support users who pull in our library via npm and bower. I was hoping to use your library as a dependency, but for the time being I will have to concat or wrap your library into mine. This is because I cannot add your lib as a dependency  for npm. This would be very useful for users of webpack and or browserify.

**Comment by thenikso** [comment]
Hi there, I'm using angular-google-maps in a project right this days :)

I've published [angular-inview to npm](https://www.npmjs.com/package/angular-inview).

Cheers
