### ISSUE TITLE
$inview allways true (horizontal scrolling)

### ISSUE THREAD

**Issue by F1ow** [thenikso/angular-inview#44]
In my case the body is set to height: 100% and I'm using the attribute in-view="show = $inview" but when I log {{show}} it's always true. My items are display: inline-block and I made sure that my window triggers the scroll event.

When I change my css to vertical scrolling it works well! Is there any setting I have to change?

Thanks,
Florian

**Comment by thenikso** [comment]
currently, horizontal scrolling is not supported. it will be if I ever find the time to complete the `develop` branch with v2 :)

**Comment by bmwertman** [comment]
Any progress on this? I have three containers in the same view port with horizontal scrolling that I need to detect the element in view for.
