### ISSUE TITLE
$event.inViewTarget is not working

### ISSUE THREAD

**Issue by pc3b3r** [thenikso/angular-inview#45]
Using AngularJS 1.3.12 I get the following error:

Referencing DOM nodes in Angular expressions is disallowed! Expression: lineInView($index, $inview, $inviewpart, $event.inViewTarget)

**Comment by thenikso** [comment]
Hi there, can you explain how you solved this? thanks!

**Comment by pc3b3r** [comment]
Just use lineInView($index, $inview, $inviewpart, $event). Then inside the controller use event.inViewTarget.

**Comment by thenikso** [comment]
thanks :+1:
