### ISSUE TITLE
Usage of directive is unreliable when using viewport CSS units (vh,vmin,vmax)

### ISSUE THREAD

**Issue by janhoogeveen** [thenikso/angular-inview#47]
In my website I've got a header with a height of 100vh. Below the header is a list of items I use the in-view directive on. I found that it incorrectly triggered the in view events.

After some debugging I found out that using the 100vh css unit produces unreliable results for the getBoundingClientRect() method. It returned this value:
```
{
  bottom: 58,
  height: 102,
  left: 144.5,
  right: 320.5,
  top: -44,
  width: 176
}
```

When I change the header to use a percentage unit (100%) the values are far more reliable:

```
{
  height: 102,
  width: 176,
  left: 144.5,
  bottom: 955,
  right: 320.5
}
```

This bug occurs on Chrome Version 41.0.2272.104 (64-bit) on Mac OS 10.10.2 (Yosemite).

**Comment by janhoogeveen** [comment]
Actually, disregard that. After further testing I found out that the getBoundingClientRect() method also takes CSS transforms into account. I have a view animation that uses a translate and opacity transform. After disabling this the directive is working like a charm.

**Comment by thenikso** [comment]
:+1:
