### ISSUE TITLE
in view not working

### ISSUE THREAD

**Issue by adelsedighi** [thenikso/angular-inview#50]
I have implemented in-view directive in my code , but I just want the view-port displaying content to be on page, to decrease page load, does this directive help me to solve this issue??
the documentation is somehow weak, could you please put some sample working file?
I have  <any in-view> my repeating blocks are several ng-repeat blocks</any>

**Comment by thenikso** [comment]
The initial issue this directive wanted to solve was the "infinite scrolling" one. You can find examples for that usage (which from what I understand is something you are also trying to achieve) in the [examples](https://github.com/thenikso/angular-inview/tree/master/examples) folder. Feel free to open again this issue if you need more support
