### ISSUE TITLE
$hasBeenInView? property

### ISSUE THREAD

**Issue by JaKXz** [thenikso/angular-inview#53]
I think it would be a welcome addition to track whether or not an element with the `in-view` attribute has been in view at least once.

This way, I could have a callback function that only executes once [per session]:

```jade
.button(in-view='!$hasBeenInView && $inview && doSomething()')
```

**Comment by thenikso** [comment]
You can easily achieve this with something like:

```
<any in-view="hasBeenInView = hasBeenInView||$inview"></any>
```

and use the `hasBeenInView` for whatever you need.
