### ISSUE TITLE
[NPM] angular-inview published as 1.5.0 is in fact 2.0-alpha1

### ISSUE THREAD

**Issue by jrencz** [thenikso/angular-inview#55]
it has the following banner:

```
// # Angular-Inview
// - Author: [Nicola Peduzzi](https://github.com/thenikso)
// - Repository: https://github.com/thenikso/angular-inview
// - Install with: `bower install angular-inview`
// - Version: **2.0-alpha1**
```

Could you please release the right version?

**Comment by jrencz** [comment]
@thenikso it seems you published from develop ;)

**Comment by thenikso** [comment]
I didn't publish but apparently someone did! Anyway, the master package.json should now have been updated.

**Comment by jrencz** [comment]
@thenikso could you please publish the 2.0.0-alpha.x as well? It's more reliable to depend on a pre-release than to depend on git reference as I have to do now.
