### ISSUE TITLE
Wrong branch on NPM

### ISSUE THREAD

**Issue by sinak** [thenikso/angular-inview#62]
Running `npm install angular-inview` installs what is purportedly version 1.5.0, but is in fact 2.0-alpha1.

2.0-alpha1 doesn't work properly (debounce, $event and $inviewpart are all broken. This caused a couple of hours of wasted time for me as I tried to figure out if it was a problem with my code that was causing the issue.

Perhaps you could try releasing 1.5.1 with no changes and seeing if that updates npm?

**Comment by sinak** [comment]
It looks like the package belonds to user "angular-inview." If that's not you Nik, you You might also try contacting support@npmjs.com to ask them to make you the owner.

**Comment by thenikso** [comment]
The tag was indeed quite old. I updated it. I'll keep an eye on npm to see if it updates as well.
