### ISSUE TITLE
Combine with animate.css or nganimate

### ISSUE THREAD

**Issue by josoroma** [thenikso/angular-inview#64]
it is possible to use this module with animate.css or nganimate to produce a fade to the element ".text-headline"?

```
<h1 in-view="inviewHandler($inview, 'text-headline')" class="text-headline">Hola</h1>
```

Thanks in advance.

**Comment by thenikso** [comment]
You can use this with angular animate. Assuming you have the animation on the class `i-am-in-view`:

```
<h1 in-view="thisIsInView = $inview" ng-class="{ 'i-am-in-view':thisIsInView }">Hola</h1>
```

**Comment by josoroma** [comment]
Grea!

**Comment by matewilk** [comment]
Just for the record, for some reason it doesn't play well with Animate.css and when you inview, the animated element blinks (shows up) for a millisecond and than starts the animation as suppose to. It's not angular-inview bug, and by writing the animation myself it works like a charm.
