### ISSUE TITLE
Can i preload data?

### ISSUE THREAD

**Issue by rayout** [thenikso/angular-inview#70]
When scrolling down or up, i need to preload data before the object gets in to view.
If i use offset:100px, it load after object gets in view by 100px. If i use negative offset, it does not work.

As I understand, jquery.inview plugin can do that if i need to preload images or something else.

**Comment by jhpommier** [comment]
I use this config :
`in-view-options="{offsetTop: '-400', offsetBottom: '400'}"`
and it works for me.
