### ISSUE TITLE
$inviewpart not precise

### ISSUE THREAD

**Issue by ahmehri** [thenikso/angular-inview#72]
I have a scrollable in-view-container container that contains an in-view element. The $inviewpart works properly by indicating that the `top`, `neither` and `bottom` parts of the element are, respectively, in the viewport. However when opening the chrome dev tools and dock it to the right, the $inviewpart is not precise anymore, its value is `top` (when the top of the element is in the viewport) and then `bottom`, which is wrong because the correct value should be `neither`.
I know that this may be not so important (closing the chrome dev tools will solve the problem), but this has a huge impact when designing a responsive interface, if the logic of in viewport testing rely on $inviewpart, then it won't work for device case.

**Comment by thenikso** [comment]
should be fixed in v2
