### ISSUE TITLE
Would love for $inview to be available like $index is

### ISSUE THREAD

**Issue by Deklin** [thenikso/angular-inview#75]
Basically we just want to control ng-src loading based on whether the image is in the viewport or not.

in-view directive doesn't quite deal with what we need, however if $inview was available we could do something like

ng-src='{{$inview ? item.icon : '');

**Comment by elmalto** [comment]
Not 100% what you suggest, but why not manually expose it:
```
in-view="item.inview = $inview" ng-src="{{item.inview ? item.icon : ' '}}"
```

**Comment by thenikso** [comment]
yep, that's it
