### ISSUE TITLE
You should consider adding at least one example and/or codepen

### ISSUE THREAD

**Issue by kennethlynne** [thenikso/angular-inview#76]
"The in-view attribute must contain a valid AngularJS expression to work" -> 

```html
<any in-view="doShit($inview)"></any>
```
?

**Comment by aliyeysides** [comment]
+1

**Comment by enrichit** [comment]
I kind of agree but there are examples in the examples folder of the repository.

    <li ng-repeat="t in testLines" in-view="lineInView($index, $inview, $inviewpart)">This is test line #{{$index}}</li>
