### ISSUE TITLE
Compatibility with grid CSS directives of Bootstrap

### ISSUE THREAD

**Issue by mbiermann** [thenikso/angular-inview#88]
Hi, I am using Bootstrap to manage responsiveness of my frontend in Angular. I am using the hidden-xs vs. the hidden-md classes to distinguish between either container content with individual grid size settings to be shown. I found that containers that have an active hidden-xx class assigned still fire up the inview directive. Any idea how to work around this and only trigger the directive for the container actually shown? Thanks a bunch!

**Comment by mbiermann** [comment]
Fixed it by wrapping the container contents inside another container and assigning the directive to this one instead.

**Comment by thenikso** [comment]
with an `ng-if`! The safest way is to remove the element all together. Hiding it might indeed not work at all
