### ISSUE TITLE
$inview always true when using with ng-show

### ISSUE THREAD

**Issue by stilllife00** [thenikso/angular-inview#93]
$inview is always true when using with ng-show (when the element or the wrapper is display: none)

Here a codepen to show what I mean: [PEN](http://codepen.io/stilllife00/pen/oxOqZQ)

Any workaround ? I would expect it to return false until the ng-show evaluates to true...

**Comment by fofiedelly** [comment]
HI @stilllife00, 
It seems like the variable $inview is simply ignored and not exists more.
i try to hack the code and find why but not found a way to solve it. Did you find a solution ??
Regards,

**Comment by stilllife00** [comment]
It works if used without ng-show. I had to refactor my code to take this into account

**Comment by thenikso** [comment]
Good to know, how did you refactor your code? I immagine having the `ng-show` on another element?

closing

**Comment by dbrgn** [comment]
I'm having the same problem. I have two tabs with lists in them. The inactive one is hidden using ng-show, so none of the elements should be visible. But inview reports them all as visible and triggers the callback.

If I switch to ng-if, everything works fine.

Would be great if a fix can be found, I spend quite some time debugging this issue.
