### ISSUE TITLE
Does not trigger when element scrolled into view via key events

### ISSUE THREAD

**Issue by mattdeckard** [thenikso/angular-inview#97]
If you scroll an element into view using the keyboard (i.e. up/down or PgUp/PgDown keys), the inview expression is not evaluated.

I am going to try to fix this and submit a pull request later today.

**Comment by mattdeckard** [comment]
Whoops, for some reason merging this into my forked repo closed the issue.

**Comment by thenikso** [comment]
Will keep track of this in the PR. We might think of having it in v2 or maybe have an option to specify custom events to watch
